### PR TITLE
Basic app and camera

### PR DESCRIPTION
**Pull request by tuckerjacob20**
# Additions
- created basic app
- take a picture

### CODE REVIEW

**Comment by maneesht** [comment]
Make sure you only include the needed XML files. The reset show the link between your directory and the project, which will change from computer to computer.
Here's a good gitignore:
http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project

**Comment by tuckerjacob20** [comment]
I used the default .gitignore. Should I include all of ".ideas"?

**Comment by maneesht** [comment]
Probably should contain: 
*.iml
.idea
#.idea/workspace.xml - remove # and delete .idea if it better suit your needs.
.gradle
build/

**Comment by tuckerjacob20** [comment]
I think the problem is that the project is an extra layer deep. I should have fixed the gitignore with this newest commit. What do I do about the random files that are already commited?

**Comment by maneesht** [comment]
The .gitignore should automatically remove those files after you squash.

**Comment by maneesht** [comment]
It currently does not save to the device. I can fix this though...

**Comment by tuckerjacob20** [comment]
Right, the save was the next step. I just wanted to push it up since the first bit worked.  For whatever reason my .gitignore won't get rid of them.  I'm going to push up what I have right now. Could you figure out the culprit once I do?

**Comment by maneesht** [comment]
Yes, of course.

**Pull request closed without merging**
